version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ilovepostgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend 
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=ilovepostgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - FETCH_FOX_API_KEY={your_api_key}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
